net:
  wangjifeng:
    host: 127.0.0.1
server:
  port: 8080 # 应用端口
  servlet:
    context-path: /butterflytri # 应用映射
spring:
  application:
    name: redis # 应用名称
  redis:
    host: ${net.wangjifeng.host} # redis地址
    port: 6379 # redis端口，默认是6379
    timeout: 10000 # 连接超时时间（ms）
    database: 0 # redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    jedis: # 使用连接redis的工具-jedis
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0