server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: consumer
  rabbitmq:
    host: 127.0.0.1 # rabbitmq地址
    port: 5672 # 端口号默认是5672，后端监控平台默认是15672，账户密码同下
    username: guest # 用户名
    password: guest # 密码
    virtual-host: / # 主机，rabbitmq拥有主机的概念，你可以创建主机，设置不同的密码，你可以当作分组的概念去理解