net:
  wangjifeng:
    databaseurl-port: 127.0.0.1:3306 # 数据库端口
    database-name: student_db # 数据库名
server:
  port: 8080
  servlet:
    context-path: /jpa
spring:
  application:
    name: jpa
  datasource:
    url: jdbc:mysql://${net.wangjifeng.databaseurl-port}/${net.wangjifeng.database-name}?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource # 数据源连接池类型